version: '3.9'

services:
  app:
    build:
      context: . 
      dockerfile: Dockerfile
    ports:
      - "3000:3000" 
    volumes:
      - feed-data:/data
    environment:
      NODE_ENV: "production"
      FEEDGEN_PORT: 3000
      FEEDGEN_LISTENHOST: "localhost"
      FEEDGEN_SQLITE_LOCATION: ":memory:"
      FEEDGEN_SUBSCRIPTION_ENDPOINT: "wss://bsky.network"
      FEEDGEN_HOSTNAME: "example.com"
      FEEDGEN_PUBLISHER_DID: "did:plc:abcde...."
      # FEEDGEN_SERVICE_DID: "did:plc:abcde..." 
      FEEDGEN_SUBSCRIPTION_RECONNECT_DELAY: 3000
      USER_HANDLE: ""
      APP_PASSWORD: ""

volumes:
  app-data:
    driver: local
